### ISSUE TITLE
API

### ISSUE THREAD

**Issue by dariogonle** [CMU-CREATE-Lab/video-labeling-tool#14]
Hello,

I was working on a project in which I could really use images with smoke and water vapor, could I use these images? If so, is there an API with which I can download the images. I would like to select the facility, date, whether there is smoke, steam or both, etc.

Thank you very much.

**Comment by yenchiah** [comment]
Sorry that I missed this issue. You can find the dataset in the [deep-smoke-machine](https://github.com/CMU-CREATE-Lab/deep-smoke-machine) repository.
